<?php get_header(); $demo = lockegames_demo_posts(); ?>
<main id="main-content" class="site-main">
  <section class="hero" aria-labelledby="hero-title">
    <span class="eyebrow">A revista gamer do seu jeito</span>
    <?php if (have_posts()) : the_post(); ?>
      <div class="hero-grid"><article class="featured-story"><a href="<?php the_permalink(); ?>"><img src="<?php echo esc_url(lockegames_image(0)); ?>" alt="<?php the_title_attribute(); ?>"><div class="featured-copy"><span class="eyebrow"><?php echo esc_html(get_the_category()[0]->name ?? 'Destaque'); ?></span><h1 id="hero-title"><?php the_title(); ?></h1><span class="meta"><?php echo esc_html(get_the_date('j \d\e F \d\e Y')); ?> · <?php echo esc_html(get_the_time('H:i')); ?></span></div></a></article>
        <div class="side-stories">
          <?php $side = new WP_Query(array('posts_per_page' => 2, 'offset' => 1)); if ($side->have_posts()) : while ($side->have_posts()) : $side->the_post(); ?><article class="mini-story"><a href="<?php the_permalink(); ?>"><img src="<?php echo esc_url(lockegames_image(1)); ?>" alt="<?php the_title_attribute(); ?>"></a><div class="mini-copy"><span class="meta"><?php echo esc_html(get_the_date('j \d\e F')); ?></span><h2><a href="<?php the_permalink(); ?>"><?php the_title(); ?></a></h2></div></article><?php endwhile; wp_reset_postdata(); else : foreach (array_slice($demo, 1, 2) as $post) : ?><article class="mini-story"><a href="<?php echo esc_url($post['url']); ?>"><img src="<?php echo esc_url(lockegames_image($post['image'])); ?>" alt=""></a><div class="mini-copy"><span class="meta"><?php echo esc_html($post['date']); ?></span><h2><a href="<?php echo esc_url($post['url']); ?>"><?php echo esc_html($post['title']); ?></a></h2></div></article><?php endforeach; endif; ?></div>
      </div>
    <?php else : ?><div class="hero-grid"><article class="featured-story"><a href="#"><img src="<?php echo esc_url(lockegames_image(0)); ?>" alt=""><div class="featured-copy"><span class="eyebrow">Notícias</span><h1 id="hero-title"><?php echo esc_html($demo[0]['title']); ?></h1><span class="meta"><?php echo esc_html($demo[0]['date']); ?></span></div></a></article><div class="side-stories"><?php foreach (array_slice($demo, 1, 2) as $post) : ?><article class="mini-story"><a href="#"><img src="<?php echo esc_url(lockegames_image($post['image'])); ?>" alt=""></a><div class="mini-copy"><span class="meta"><?php echo esc_html($post['date']); ?></span><h2><a href="#"><?php echo esc_html($post['title']); ?></a></h2></div></article><?php endforeach; ?></div></div><?php endif; ?>
  </section>
  <section class="section" aria-labelledby="latest-title"><div class="section-heading"><h2 id="latest-title">Publicações recentes</h2><a class="button" href="<?php echo esc_url(get_post_type_archive_link('post') ?: home_url('/')); ?>">Ver tudo</a></div><div class="article-grid">
    <?php $latest = new WP_Query(array('posts_per_page' => 6)); if ($latest->have_posts()) : while ($latest->have_posts()) : $latest->the_post(); ?><article class="article-card"><a href="<?php the_permalink(); ?>"><img src="<?php echo esc_url(lockegames_image(get_the_ID())); ?>" alt="<?php the_title_attribute(); ?>"></a><span class="meta"><?php echo esc_html(get_the_date('j \d\e F \d\e Y')); ?></span><h3><a href="<?php the_permalink(); ?>"><?php the_title(); ?></a></h3><p><?php echo esc_html(wp_trim_words(get_the_excerpt(), 14)); ?></p></article><?php endwhile; wp_reset_postdata(); else : foreach ($demo as $post) : ?><article class="article-card"><a href="<?php echo esc_url($post['url']); ?>"><img src="<?php echo esc_url(lockegames_image($post['image'])); ?>" alt=""></a><span class="meta"><?php echo esc_html($post['date']); ?></span><h3><a href="<?php echo esc_url($post['url']); ?>"><?php echo esc_html($post['title']); ?></a></h3><p>Notícias, ideias e descobertas para quem vive o universo dos games.</p></article><?php endforeach; endif; ?></div></section>
  <section class="category-band" aria-labelledby="free-title"><div class="section-heading"><h2 id="free-title">Jogos grátis</h2><a class="button" href="<?php echo esc_url(home_url('/?s=jogos+grátis')); ?>">Ver tudo</a></div><div class="article-grid"><?php foreach (array_slice($demo, 3, 3) as $post) : ?><article class="article-card"><a href="<?php echo esc_url($post['url']); ?>"><img src="<?php echo esc_url(lockegames_image($post['image'])); ?>" alt=""></a><span class="meta"><?php echo esc_html($post['date']); ?></span><h3><a href="<?php echo esc_url($post['url']); ?>"><?php echo esc_html($post['title']); ?></a></h3></article><?php endforeach; ?></div></section>
</main><?php get_footer(); ?>
